remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Informe de la pr치ctica 1: configuraci칩n del IaaS"
author: Sergio Perera M치rquez
description: Esto es un informe para una pr치ctica
